### ISSUE TITLE
Cant join channel - couchDB crashing

### ISSUE THREAD

**Issue by gtpaulose** [everledger/fabkit#4]
**Describe the bug**
Cannot join channel with the following error, 

```       
[ERROR] Error joining channel mychannel
[ERROR] Error: error getting endorser client for channel: endorser client failed to connect to peer0.org1.example.com:7051: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 172.19.0.2:7051: connect: connection refused"
```

Also realised that the couchDB container is crashing, unsure whether the two are related

**To Reproduce**
1. Run `fabkit network start`

**Expected behavior**
Peers should be able to join the channel

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.2
 - Chip: Apple M1
 - Docker: 20.10.8
 - Docker Compose: 2.0.0

**Comment by czar0** [comment]
Apparently, there are no `fabric-couchdb` working versions for Apple M1 at the moment (all the versions I tried are crashing). It seems that M1 users will need to run the recently supported official `couchdb:3.1.x` image instead. I am updating the troubleshooting section in the README with this finding.
