### ISSUE TITLE
can not install in Ubuntu 20.04.3 LTS x86_64 

### ISSUE THREAD

**Issue by ZoomQuiet** [everledger/fabkit#7]
**Describe the bug**
[ERROR] tar: Error is not recoverable

**To Reproduce**
1. Install the app by running this command `bash <(curl -sL https://raw.githubusercontent.com/everledger/fabkit/master/install.sh)`
2. Where would you like to install Fabkit? [/home/zoomq/.fabkit] /home/zoomq/.fabkit

[ERROR] tar: Error is not recoverable: exiting now
[ERROR] There was an error extracting fabkit-latest.zip into /home/zoomq/.fabkit
❌

**Expected behavior**

**Screenshots**

![](https://ipic.zoomquiet.top/2021-12-08-zshot%202021-12-08%2021.58.37.jpg)

**Logs**
Clean your terminal, run the same command in debug mode (`-d, --debug`) and paste the whole content of your shell (please wrap the text in a "code snippet" by using opening and closing with 3 backticks).

Copy and paste also the result of `cat ${FABKIT_ROOT}/.log`.

2021-12-08 13:55:16 UTC [ERROR] tar: Error is not recoverable: exiting now
2021-12-08 13:55:16 UTC [ERROR] There was an error extracting fabkit-latest.zip into /home/zoomq/.fabkit
2021-12-08 13:55:42 UTC [ERROR] There was an error extracting fabkit-latest.zip into /home/zoomq/.fabkit
2021-12-08 13:55:42 UTC [ERROR] tar: Error is not recoverable: exiting now
2021-12-08 14:03:06 UTC [ERROR] tar: Error is not recoverable: exiting now
2021-12-08 14:03:06 UTC [ERROR] There was an error extracting fabkit-latest.zip into /home/zoomq/.fabkit

**Config**
Paste here the result of `cat ${FABKIT_ROOT}/.lastrun`.

> not yet there...

**Environment**
Be as specific as possible!
```
OS: Ubuntu 20.04.3 LTS x86_64
Host: Droplet 20171212
Kernel: 5.4.0-91-generic
Uptime: 1 day, 10 hours, 16 mins
Packages: 1220 (dpkg)
Shell: bash 5.0.17
Terminal: /dev/pts/0
CPU: DO-Premium-Intel (2) @ 2.494GHz
GPU: 00:02.0 Red Hat, Inc. QXL paravirtual graphic card
Memory: 766MiB / 1987MiB
```

$ docker --version
Docker version 20.10.11, build dea9396

$ docker-compose --version
docker-compose version 1.25.0, build unknown

**Additional context**

**Comment by ZoomQuiet** [comment]
read install.sh base git repo. installed

![](https://ipic.zoomquiet.top/2021-12-08-zshot%202021-12-08%2022.18.38.jpg)

**Comment by ZoomQuiet** [comment]
<img width="920" alt="wecom-temp-99d02764fc953f247a67c92e9e6b06bf" src="https://user-images.githubusercontent.com/22494/145227006-b3cd0472-c4b5-4bb4-8112-9a9a3ab656fd.png">

but, can usage fabkit, also...

**Comment by czar0** [comment]
hi @ZoomQuiet, thanks for reporting this bug. In order to help you in solving it, could you please provide the following information:

- Output of `tar --version`
- Output of `bash --version`

Furthermore, please download the [codebase tarball](https://github.com/everledger/fabkit/archive/refs/heads/master.zip) and in the same directory run `mkdir tempdir && tar -C "tempdir" -xzf master.zip` and paste the output in comments.

**Comment by ZoomQuiet** [comment]
> hi @ZoomQuiet, thanks for reporting this bug. In order to help you in solving it, could you please provide the following information:
> 
> * Output of `tar --version`
> * Output of `bash --version`
> 
> Furthermore, please download the [codebase tarball](https://github.com/everledger/fabkit/archive/refs/heads/master.zip) and in the same directory run `mkdir tempdir && tar -C "tempdir" -xzf master.zip` and paste the output in comments.

> for debug chinese export , config system as LANG="zh_CN.UTF-8"

$ tar --version
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
许可证 GPLv3+：GNU GPL 第 3 版或更新版本 <https://gnu.org/licenses/gpl.html>
这是自由软件：您可以自由地更改并对其重新发布。
在法律所允许的范围内不含任何担保。

由 John Gilmore 和 Jay Fenlason 所写。

$ bash --version
GNU bash，版本 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
许可证 GPLv3+: GNU GPL 许可证第三版或者更新版本 <http://gnu.org/licenses/gpl.html>

本软件是自由软件，您可以自由地更改和重新发布。
在法律许可的情况下特此明示，本软件不提供任何担保。

and re-try that line:

```
(base) zoomq @ ubuntu-s-1vcpu-2gb-sgp1-01 ~/go/src/github.com

$ axel https://github.com/everledger/fabkit/archive/refs/heads/master.zip
正在初始化下载：https://github.com/everledger/fabkit/archive/refs/heads/master.zip
File size: unavailable
正在打开输出文件 fabkit-master.zip
服务器不支持，使用单个连接从头下载。
正在开始下载

[ N/A]  .......... .......... .......... .......... ..........  [ 172.7KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [ 332.1KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [ 492.5KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [ 652.4KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [ 810.9KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [ 964.1KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [1114.6KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [1269.2KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [1417.5KB/s]
[ N/A]  .......... .......... .......... .......... ..........  [1566.2KB/s]
[ N/A]  .
连接 0 完成下载

已下载 501.438 千字节，用时 0 second(s)。（1566.25 KB/s）

$ mkdir tempdir && tar -C "tempdir" -xzf master.zip
tar (child): master.zip：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

$ mkdir tempdir && tar -C "tempdir" -xzf fabkit-master.zip
mkdir: 无法创建目录 “tempdir”: 文件已存在

$ ls
dev4fab  fabkit  fabkit-master.zip  tempdir  zoomquiet

$ rm -rf tempdir

$ mkdir tempdir && tar -C "tempdir" -xzf fabkit-master.zip
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
same ERROR ...

**Comment by czar0** [comment]
@ZoomQuiet these two issues should now be fixed🤞 . I am giving you a brief explanation of the whys and changes made:
- The install script was using the executable `tar` whose implementation on Ubuntu (and other Linux distros) [does not support `zip` files](https://stackoverflow.com/questions/28951285/error-when-tar-a-zip-on-linux). The code is now fetched with `git clone`.
- When running Fabkit, dependency versions are retrieved and checked at runtime from your system and some of those need to be parsed from a raw string. This is the case for the `bash` binary which `--version` result is in your case `GNU bash，版本 5.0.17(1)-release (x86_64-pc-linux-gnu)`. Space splitting via `cut` is not working correctly with non-ASCII characters and the resulting output of that operation was an empty string. I provided a quick fix for it in addition to printing the installed version together with the required one in case of error.

I tested these changes on a Ubuntu 20.04 docker container, but before merging these changes I want to ask you to try them out on your side as well.
Please clone this repository one more time (or pull the latest changes) and switch to this branch: `git checkout bugfix/install-and-run-on-ubuntu-20-04`.
You can test the `install.sh` script directly by running `bash <(curl -sL https://raw.githubusercontent.com/everledger/fabkit/bugfix/install-and-run-on-ubuntu-20-04/install.sh)`  .

**Comment by ZoomQuiet** [comment]
Yes, can install well;
![zshot 2021-12-15 12 04 16](https://user-images.githubusercontent.com/22494/146121543-3c66e407-e9c0-49ae-9d8c-4e1677c82be8.jpg)

but, can not run, need bash >= 4.2, but, my env is 5.0.17(1)-release (x86_64-pc-linux-gnu)
![zshot 2021-12-15 12 08 01](https://user-images.githubusercontent.com/22494/146121555-f276ede9-d513-41e0-b835-8439ecf2fdb6.jpg)

**Comment by czar0** [comment]
@ZoomQuiet could you confirm you checked out the correct branch after the installation? Please run this command within the `FABKIT_ROOT` and try again:

```bash
git checkout bugfix/install-and-run-on-ubuntu-20-04
```
